env:
  global:
    - CC_TEST_REPORTER_ID=c27f6e57b2bc42a15a967b56709a9534b0da9d7c41f766e9dec73c1cda667323
language: ruby
rvm:
  - 2.6.5
services:
  - postgresql
addons:
  postgresql: "10"
bundler_args: --jobs=2
script:
  - bin/rails db:environment:set RAILS_ENV=test
  - bin/rails db:test:prepare
  - bin/rails db:migrate --trace RAILS_ENV=test
  - bundle exec rspec --format doc
cache: bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/travis.database.yml config/database.yml
  - cp config/settings/test.yml.sample config/settings/test.yml
  - cp example.env .env
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT