# Install python and aptitude on the target machines (apt-get install python aptitude)
# Copy ssh public key to machines (ssh-copy-id user@host)
---
- name: Install Rails Server
  hosts: all
  # After initial provisioning, use vagrant instead of root
  # remote_user: root
  remote_user: vagrant
  become: yes
  # become_method: sudo
  gather_facts: no # don't gather facts because /usr/bin/python isn't set
  pre_tasks:
    - name: apt-get update
      raw: apt-get update -qq
    - name: install python 2.7 and aptitude
      raw: apt-get install -qq python2.7 aptitude
    - name: set python 2.7 as default
      raw: update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
    - name: Create postgres user for tilde
      become: yes
      become_user: postgres
      postgresql_user:
        name: tilde
        password: tilde
        role_attr_flags: CREATEDB,SUPERUSER
    - name: Ensure we have access from the new user
      become: yes
      become_user: postgres
      postgresql_privs:
        db: tilde
        role: tilde
        objs: ALL_IN_SCHEMA
        privs: ALL
        state: absent
  roles:
    - common
    - deploy-user
    - { role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.5.1'],
        rvm1_user: 'vagrant'
      }
    - geerlingguy.postgresql
    - nginx
    - rails
    - monit
    - memcached
    - redis
    - hashbangcode.imagemagick
    # - certbot
    # - elasticsearch
